[build]
  base = "packages/archive"
  publish = "."

# Dispays a promo banner across the index and all archived surveys
# see: packages/archive/netlify/edge-functions/survey-banner.ts
#[[edge_functions]]
#  function = "survey-banner"
#  path = "/*"
