<script lang="ts">
	import MiniMap from './lib/MiniMap.svelte'
	import Pager from './lib/Pager.svelte'
</script>

<MiniMap />

<main class="shell">
	<div class="intro">
		<p>
			<strong>This is not a live survey.</strong> This is a preview of the Stack Overflow Developer Survey which shows the logic used to display
			questions. The intended use is for debugging and historical archive.
		</p>
		<p>
			The URL of this page will vary and is based on the branch name i.e., archived versions will usually contain the year. The current
			question list can always be found at <a href="https://questions.survey.stackoverflow.co/">questions.survey.stackoverflow.co</a>.
		</p>
		<p>
			You can find more information in the <a href="https://github.com/StackExchange/Survey/">GitHub repo</a> where this app is generated by
			<code>packages/survey</code>.
		</p>
	</div>
	<Pager />
</main>

<style>
	.intro {
		margin: 100px auto;
		max-width: 960px;
	}
	.intro p {
		margin-bottom: 10px;
	}
	.intro strong {
		text-decoration: underline;
	}
	.shell {
		padding: 2rem 1.5rem 5rem;
		box-sizing: border-box;
		min-width: 0;
		width: 70%;
	}
</style>
