/**
 * AUTOGENERATED — do not edit by hand.
 * Source: questions/question.schema.json + questions/survey.schema.json
 * Regenerate with `npm run gen:types -w survey`.
 */

export type ShowIf =
	| {
			/**
			 * @minItems 1
			 */
			any: [ShowIf, ...ShowIf[]];
	  }
	| {
			/**
			 * @minItems 1
			 */
			all: [ShowIf, ...ShowIf[]];
	  }
	| {
			not: ShowIf;
	  }
	| {
			[k: string]: string | [string, ...string[]];
	  };

/**
 * One question file under questions/. Filename must match question.id.
 */
export interface SurveyQuestion {
	question: {
		/**
		 * Stable identifier; used as the Qualtrics DataExportTag and as the filename.
		 */
		id: string;
		/**
		 * Survey release version this question shipped under, e.g. 2025.1.
		 */
		version: string;
		/**
		 * The prompt as Markdown. **bold**, *italic*, [text](url), and `- ` lists are supported.
		 */
		title: string;
		type: "single_select" | "multi_select" | "nps" | "free_text" | "rank" | "scale" | "display" | "meta";
		required: boolean;
		/**
		 * Optional. Implicit default false. Set to true to mark a question retired but kept on file.
		 */
		deprecated?: boolean;
		/**
		 * Optional. Implicit default [].
		 */
		tags?: string[];
		/**
		 * Optional. Implicit default "". Why this question exists / what it tracks.
		 */
		rationale?: string;
		/**
		 * Optional. Implicit default []. Year-by-year changelog of edits.
		 */
		history?: {
			version: string;
			changes: string;
		}[];
		/**
		 * Render variant for type:single_select.
		 */
		display?: "dropdown";
		/**
		 * Required for type:free_text.
		 */
		lines?: "single" | "multi";
		/**
		 * Shuffle option order; pin any text_entry choice to the end.
		 */
		randomize?: boolean;
		validate?: {
			type: "number" | "email" | "phone" | "zip" | "date";
			min?: number;
			max?: number;
			decimals?: number;
		};
		/**
		 * NPS-style scale lower bound.
		 */
		scale_min?: number;
		/**
		 * NPS-style scale upper bound.
		 */
		scale_max?: number;
		scale_labels?: {
			min?: string;
			max?: string;
		};
		/**
		 * Required for type:scale.
		 */
		scale?: {
			multiple: boolean;
			/**
			 * @minItems 1
			 */
			columns: [string, ...string[]];
		};
		options?: (
			| string
			| {
					label: string;
					/**
					 * Override the implicit slug; only used by show_if references. Must start with a letter or underscore (digit-leading keys get number-parsed by some YAML 1.1 tools).
					 */
					key?: string;
					/**
					 * Free-input choice (the 'Other (please specify)' pattern).
					 */
					text_entry?: boolean;
			  }
		)[];
		show_if?: ShowIf;
	};
}

export type FlowElement =
	| {
			block: string;
			pages: PageEntry[];
	  }
	| {
			randomize: number;
			even_presentation?: boolean;
			/**
			 * @minItems 1
			 */
			blocks: [FlowElement, ...FlowElement[]];
	  }
	| {
			if: unknown;
			then: FlowElement[];
	  };
/**
 * One page within a block. A single id, a list of ids on the same page, or an if/then wrapping a list of pages that should only show when the condition holds.
 */
export type PageEntry =
	| string
	| [string, ...string[]]
	| {
			if: unknown;
			/**
			 * @minItems 1
			 */
			then: [PageEntry, ...PageEntry[]];
	  };

/**
 * Top-level survey.yaml: the flow Qualtrics presents to respondents.
 */
export interface SurveyStructure {
	flow: FlowElement[];
	[k: string]: unknown;
}

