// Generate src/lib/data/types.generated.ts from the JSON schemas.
// Run with `npm run gen:types -w survey`. Re-run after editing either schema.

import { compileFromFile } from 'json-schema-to-typescript'
import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '../../..')
const out = resolve(here, '../src/lib/types/generated.ts')

const banner = `/**
 * AUTOGENERATED — do not edit by hand.
 * Source: questions/question.schema.json + packages/survey/survey.schema.json
 * Regenerate with \`npm run gen:types -w survey\`.
 */`

const opts = {
	bannerComment: '',
	additionalProperties: false,
	style: { tabWidth: 2, useTabs: true, singleQuote: false, semi: true },
	declareExternallyReferenced: true,
	unknownAny: true,
} as const

const [questionTypes, surveyTypes] = await Promise.all([
	compileFromFile(resolve(repoRoot, 'questions/question.schema.json'), opts),
	compileFromFile(resolve(here, '../survey.schema.json'), opts),
])

writeFileSync(out, `${banner}\n\n${questionTypes}\n${surveyTypes}\n`)
console.log(`wrote ${out}`)
